### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by gtirloni**

### CODE REVIEW

**Comment by gtirloni** [comment]
Do I need to rebase my branch with some other branch other than 'master' so this builds?

**Comment by simonbates** [comment]
Yeah, I think that you'll need https://github.com/GPII/nexus/pull/9

Could we maybe figure that one out and get it merged?

**Comment by gtirloni** [comment]
ok to test

**Comment by gtirloni** [comment]
ok to test

**Comment by amatas** [comment]
ok to test

**Comment by amatas** [comment]
ok to test

**Comment by gtirloni** [comment]
Because working with Docker volume (binds or named volumes) is kind of a nightmare with UID/GID mapping, I've moved the tests command into the Dockerfile so it's all self-contained. This should minimize surprises and won't make the image any bigger.

If/when the Nexus adopts test coverage and other reports, we can switch to use Docker multi-stage builds so the first stage builds and tests and the last one just builds the image that's fit for production.

@simonbates could you help review this (or know someone who could)? Thanks in advance!

**Comment by gtirloni** [comment]
Closing in favor of https://github.com/fluid-project/infusion-nexus/pull/26

**Pull request closed without merging**
