### PR TITLE
GPII-2167: Update Nexus vars.yml to Node.js LTS

### PR DESCRIPTION
**Pull request by simonbates**

### CODE REVIEW

**Comment by avtar** [comment]
@GPII/core-architecture-committers these changes are necessary for correctly provisioning Nexus VMs.

@amatas, @gtirloni I had to add [a snippet](https://github.com/gtirloni/gpii-linux/blob/8e1d9a98f29d83fb30f24f2614f32e01cd2b3817/Vagrantfile#L32-L37) to the Nexus' Vagrantfile in order to provision this VM on a Windows 10 host. It should work as-is on macOS or Linux hosts.

**Comment by amb26** [comment]
@avtar, @amatas - I was unable to get the vagrant box for this project to start up either with or without the contents of this pull. It hangs at

    default: SSH auth method: private key

The VM has started up in Virtualbox and is at the login prompt. Vagrant 1.8.4, VirtualBox 5.0.22, Windows 7 64 bit

**Comment by amatas** [comment]
Hi @amb26, Vagrant had a bug that [didn't set the SSH keys to access to the VM properly](https://github.com/mitchellh/vagrant/issues/7642). Please, try upgrading Vagrant to the [latest version](https://www.vagrantup.com/downloads.html).

**Comment by amb26** [comment]
@amatas - Vagrant 1.8.4 didn't have this bug, which is why I downgraded to it. I'm nervous to blindly upgrade vagrant to some new version that may well have other problems or be incompatible with my virtualbox since it seems they are generally careless with their release policy - without some assurance from others that they are using a particular combination. Could others chime in on this thread about which versions of Vagrant and VirtualBox they are using without problems?

**Comment by gtirloni** [comment]
I'm using Vagrant 1.9.1, VirtualBox 5.0.12 on Windows 10 (outside Cygwin)
and Fedora 25 with success.

**Comment by amatas** [comment]
@amb26 Sorry I meant [this bug](https://github.com/mitchellh/vagrant/issues/7610) that is also related to SSH keys. It was fixed in Vagrant 1.8.6. I remember this because my setup was affected by it and I had to modify a .rb file to workaround the bug.

I have these boxes working fine:
- Vagrant 1.9.1, VirtualBox 5.1.12 on Arch Linux.
- Vagrant 1.9.1, VirtualBox 5.1.10 on Mac OSX 10.12.2
- Vagrant 1.8.6, VirtualBox 5.1.6 on Windows 10

**Comment by avtar** [comment]
I tested @simonbates's changes, along with the snippet I referred to earlier, using Vagrant 1.9.1 and VirtualBox 5.1.12 on a Windows 10 host.

**Comment by the-t-in-rtf** [comment]
Where are we with this?  While we wait, can we get a dev release with this fix via fluid-publish?  I'd like to use it in projects, but am blocked by the outdated node version.

**Comment by simonbates** [comment]
I have added a workaround from @gtirloni to mount `node_modules` in `/var/tmp` to address issues in the VirtualBox shared folders.

@amb26 Would you be able to check again and see if the Vagrantfile is now working for you?

Thanks!

**Comment by gtirloni** [comment]
We need to merge this PR because the changes proposed here are not optional.

**Comment by amb26** [comment]
Ok - I'm merging this on the recognisance of others since I am still unable to test its content

**Pull request merged**
