### PR TITLE
NOJIRA: Reorganize module names and dependencies

### PR DESCRIPTION
**Pull request by hex-for-hecate**
I have done some minor renaming and rewiring of dependency chains. This is partially just to practice my understanding of Infusion and Kettle. 
In current master, we have a couple of cases where a module dependency is only satisfied because the module is included alongside that dependency in all use contexts. This is illustrated in this diagram, where I have shown explicit inclusion relationships with full arrows and direct dependencies with dashed arrows:
NexusDependencies

This is the equivalent diagram after my changes:
NexusDependenciesAfterPR

I understand there might be a reason for everything being wired the way it is currently, so I invite comments from @simonbates  and @amb26 .

### CODE REVIEW

**Comment by hex-for-hecate** [comment]
Tests fail under Ubuntu, in particular the [`require("./nexusUtils.js")` from `src/nexusGrades.js`](https://github.com/fluid-project/infusion-nexus/pull/20/files#diff-d8dd2345323ec95c71fdfef8be634cfeR16) doesn't work. I can't quite understand why, as tests pass fine on my mac, both locally and on the VM.

**Comment by amb26** [comment]
Two issues - firstly the filesystem is strongly case-sensitive on Ubuntu (and, by extension, everywhere - although I think KELLES would disagree for reasons we'd have to have a detailed discussion with him about) - so you have the file commited as NexusUtils.js rather than nexusUtils as you have referenced it - also you've left off the file extension in the require which is no doubt benign but should probably be included for clarity.
I suggest normalising the case everywhere to NexusGrades.js etc. roughly in line with how it was before although I notice we had the top-level driver nexus.js which was in lower case I guess following the precedent of other such drivers as index.js etc. but who knows : P

**Comment by hex-for-hecate** [comment]
How strange. On my machine the file is camel-cased, and there's no unstaged work. I see that the rename isn't in the commit though. **Edit:** looks like, amazingly, git does not consider changing the capitalization in a file name to be a modification of that file. This can be fixed by using `git rm --cached` or `touch`.

I prefer normalizing to `nexusGrades`, `nexusUtils`, etc. This is more internally consistent with grade names. Any issues with that?

**Comment by simonbates** [comment]
I'm not familiar with the functionality of `git` on macOS, but case-sensitivity is definitely something that varies by filesystem https://en.wikipedia.org/wiki/Case_sensitivity#In_filesystems

In regards to the file reorganization, something to think about is when and how we want to use `require` (and other code-loading mechanisms). By adding `require("./nexusUtils.js")` to `nexusGrades.js`, it makes the dependency explicit but makes it harder to run the code in an environment in which `require` is not available, such as a web browser. The idea of having a separate driver that pulls in all of the required files, is that we can offer different implementations for different environments.

**Comment by simonbates** [comment]
Though in the case of the Nexus, having a dependency on Node.js is likely fine as it's a web application.

**Comment by hex-for-hecate** [comment]
Good point about how the same dependency binding mechanisms aren't available in all environments. I wonder if there's some convention (e.g. naming, folder placement, comments) to make it clear that a system component is expected to be used in this dependency-injection style. I could personally use some low-tech way to alleviate the difficulty of tracing the relationships among bits of Infusion-y systems.

So do we consider this PR an improvement, and okay to merge?

**Comment by amb26** [comment]
I think this is definitely an improvement, and am happy to merge it but would prefer that nexusModule.js remained as index.js since this is a node module standard. If we made our own convention it would have to be some cumbersome regular one like insisting that the standard index point was derived from the package name such as infusion-nexus-module.js which probably noone would like : P
+1 for @simonbates comment that explicit "require" statements for dependents are actually a source of dependency weakness and should really be encoded in some kind of external material - either in a "config" or the index file. But indeed there are no great solutions to such problems and the Nexus as written is indeed tightly coupled to node.js.

**Comment by amb26** [comment]
As a general note per our earlier conversation whilst it is OK to have commits labelled NOJIRA it is probably a hazardous practice to issue pulls from a branch named NOJIRA which is then likely to get reused for multiple unrelated purposes.

**Pull request merged**
